apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingressgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ingressgateway.name" . }}
    app.kubernetes.io/name: {{ include "ingressgateway.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: ingressgateway
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
spec:
  ports:
    - name: status-port
      port: 15020
      protocol: TCP
      targetPort: 15020
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "ingressgateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.ingressgateway.service.type }}
